###############################################################
#  Generated by:      Cadence Innovus 19.10-p002_1
#  OS:                Linux x86_64(Host ID remote02)
#  Generated on:      Fri May 29 12:59:15 2020
#  Design:            mult8x8
#  Command:           create_ccopt_clock_tree_spec -file ccopt_clock_tree.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Clocks present at pin clk
#   clk (period 2.000ns) in timing_config typical_constraint([../../dc/mult8x8/mult8x8.syn.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner typical_dly -early -clock_tree clk 0.010

set_ccopt_property target_max_trans_sdc -delay_corner typical_dly -late -clock_tree clk 0.010
set_ccopt_property source_driver -clock_tree clk {INVX1TS/A INVX1TS/Y}
set_ccopt_property source_max_capacitance -clock_tree clk 0.005
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 2

# Skew group to balance non generated clock:clk in timing_config:typical_constraint (sdc ../../dc/mult8x8/mult8x8.syn.sdc)
create_ccopt_skew_group -name clk/typical_constraint -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/typical_constraint true
set_ccopt_property extracted_from_clock_name -skew_group clk/typical_constraint clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/typical_constraint typical_constraint
set_ccopt_property extracted_from_delay_corners -skew_group clk/typical_constraint {typical_dly typical_dly}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

